Subtask/ol 63/book genres
radosevic-dr/online_library pull request #15
Opened 2024-07-30 12:59 UTC by Ana0312

2024-07-31 15:30 UTC, marijana-codeus requested changes
@damir-tahirovic Please take a look at my comments

2024-07-31 15:30 UTC, marijana-codeus commented on app/Http/Controllers/GenreController.php
> +            $genres = Genre::paginate(10);
@damir-tahirovic You can leave 10 as a fallback (default) value, but perPage parameter should otherwise be read from the request parameters.

2024-07-31 15:30 UTC, marijana-codeus commented on app/Http/Controllers/GenreController.php
> +            }
@damir-tahirovic Pull code through some formatter. You can use Laravel Pint.

2024-07-31 15:30 UTC, marijana-codeus commented on routes/api.php
> +//Routes for genres
@damir-tahirovic Only authenticated librarians should be able to use these routes

2024-07-31 15:30 UTC, marijana-codeus commented on app/Http/Controllers/GenreController.php
> +            return response()->json($e->getMessage(),400);
@damir-tahirovic As we are developing only api maybe it would be better to return some user-friendly message.

2024-08-02 17:46 UTC, MatijaBojanic commented on app/Http/Controllers/GenreController.php
> +            $genre = Genre::findOrFail($id);
find or fail returns a 404 by default, and you are catching it and returning a 400. Why?

2024-08-07 12:12 UTC, marijana-codeus commented on app/Http/Controllers/GenreController.php
> +            return response()->json([
@damir-tahirovic If you do not specify the status code, the default is 200. Maybe it's best to get the status code directly from the exception you are catching.

2024-09-09 13:54 UTC, marijana-codeus approved these changes
Code reviewed, changes look good.

2024-09-09 16:04 UTC, merged